# Generated by Django 3.1.1 on 2020-09-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='product name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('descriptions', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='display type')),
                ('resolution', models.CharField(max_length=255, verbose_name='resolution')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='battery volume')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('sd', models.BooleanField(default=True)),
                ('sd_volume', models.CharField(max_length=255, verbose_name='Max capacity of sd')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='main camera')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='frontal camera')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='product name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('descriptions', models.TextField(null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='display type')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='processor frequency')),
                ('ram', models.CharField(max_length=255, verbose_name='RAM')),
                ('video', models.CharField(max_length=255, verbose_name='videocard')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='working time for battery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
